spring.application.name=cashify-backend
spring.datasource.url=jdbc:mysql://localhost:3306/cashify
spring.datasource.username=root
spring.datasource.password=Hero170%

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true